### ISSUE TITLE
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

### ISSUE THREAD

**Issue by fftidus** [tuarua/WebViewANE#221]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    yes
- **What version of the product are you using?**
    - What version are you using?
2.6.0
- **On what operating system?**
    - OSX, Win7, Win 8, Win10, etc?
    Win10
- **If Windows is the AIR app **32bit** or **64bit**?
    - 32bit or 64bit
32bit
- **Which IDE are you using?**
    - IntelliJ, Flash Builder, Animate, cmd line, Flash Develop etc?
Flash Builder
- **Which version of AIR are you using?**
32

- **What steps will reproduce the problem?**
    - Please provide detailed information here, enough for someone else to reprodce your problem.
debug or package
- **What is the expected output? What do you see instead?**

dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:709)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/adobe/air/TRActivityResultCallback.class

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:709)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing com/tuarua/WebViewANE.class

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

- **Does this problem also occur in the `WebViewANE` Sample Application provided?**

**Comment by tuarua** [comment]
https://github.com/tuarua/WebViewANE/wiki/Android#air-32--33

**Comment by fftidus** [comment]
Yes!
