### ISSUE TITLE
Error when dispose.

### ISSUE THREAD

**Issue by tidus2020** [tuarua/WebViewANE#242]
Answer the below. **DO NOT DELETE!!**

- **Have you read the [Wiki](https://github.com/tuarua/WebViewANE/wiki) carefully?**
    - Follow the instructions provided before raising an issue.
    
- **What version of the product are you using?**
    - What version are you using?
   2.10.0

- **On what operating system?**
    Win10
    
- **If Windows is the AIR app **32bit** or **64bit**?
    - 64bit

- **Which IDE are you using?**
    - Flash Builder

- **Which version of AIR are you using?**
    - 33.1

- **What steps will reproduce the problem?**
I dispose the ANE on the callback "jsToAsCallback", will get this error and crash.
> java.lang.IllegalArgumentException
        at com.adobe.fre.FREContext.dispatchStatusEventAsync(Native Method)
        at com.tuarua.frekotlin.FlashRuntimeExtensionsKt.dispatchEvent(FlashRuntimeExtensions.kt:32)
        at com.tuarua.frekotlin.FreKotlinController$DefaultImpls.dispatchEvent(FreKotlinController.kt:53)
        at com.tuarua.webviewane.ChromeClient.dispatchEvent(ChromeClient.kt:38)
        at com.tuarua.webviewane.ChromeClient.onProgressChanged(ChromeClient.kt:46)
        at mF.a(PG:262)
        at yJ.handleMessage(PG:262)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by tuarua** [comment]
`com.tuarua.webviewane.ChromeClient.onProgressChanged(ChromeClient.kt:46)`

This line says you are calling dispose in the middle of a page load (onProgress)

You should only call `dispose` when you are closing your app as per the example.
You are not meant to call dispose at random times

```
NativeApplication.nativeApplication.addEventListener(Event.EXITING, onExiting);

private function onExiting(event:Event):void {
    WebView.dispose();
}
```
