### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jon-reid-nz** [tuarua/WebViewANE#74]
I am running 0.24 OK, but 0.28 sample app crashes with this error

Unhandled Exception: FreSharp.Exceptions.FreTypeMismatchException: cannot get property cef
   at TuaRua.FreSharp.FreSharpHelper.ThrowFreException(FreResultSharp status, String message, FreObjectSharp freObject)
   at TuaRua.FreSharp.FreSharpHelper.GetProperty(IntPtr rawValue, String name)
   at CefSharpLib.MainController.InitView(IntPtr ctx, UInt32 argc, IntPtr[] argv)
   at CefSharpLib.FreSharpController.CallSharpFunction(String name, IntPtr& ctx, UInt32 argc, IntPtr[] argv)
   at callSharpFunction(Void* context, Void* functionData, UInt32 argc, Void** argv)

Win10, 32bit, Flash Builder, AIR 26

**Comment by tuarua** [comment]
Which dlls have you used? - The ones from 0.0.24 or 0.0.28?
The error suggests the object that is being passed as the settings param is not a Settings object

What does your .init function look like?
eg:
webView.init(WebViewANESample.target.stage, viewPort, "http://www.youtube.com", settings, 1.0, 0xF1F1F1, 1.0);

Everything is OK for me here in Win10, FB and IntelliJ, AIR 26

**Comment by jon-reid-nz** [comment]
OK working now, as I realized later I needed the cef_sharp_libs_x86 DLLs, I had ended up with a mix of 0.24 and 0.28 DLLs

Thanks
